//------------------------------------------------------------------------------
// <auto-generated>
//     Esse código foi gerado por uma ferramenta.
//
//     As alterações no arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebZi.Plataform.Data.WSnfse
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CapaAutorizacaoNfse", Namespace="http://tempuri.org/")]
    public partial class CapaAutorizacaoNfse : object
    {
        
        private WebZi.Plataform.Data.WSnfse.Autorizacao AutorizacaoField;
        
        private int GrvIdField;
        
        private string IdentificadorNotaField;
        
        private int UsuarioIdField;
        
        private bool HomologacaoField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public WebZi.Plataform.Data.WSnfse.Autorizacao Autorizacao
        {
            get
            {
                return this.AutorizacaoField;
            }
            set
            {
                this.AutorizacaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int GrvId
        {
            get
            {
                return this.GrvIdField;
            }
            set
            {
                this.GrvIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string IdentificadorNota
        {
            get
            {
                return this.IdentificadorNotaField;
            }
            set
            {
                this.IdentificadorNotaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int UsuarioId
        {
            get
            {
                return this.UsuarioIdField;
            }
            set
            {
                this.UsuarioIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public bool Homologacao
        {
            get
            {
                return this.HomologacaoField;
            }
            set
            {
                this.HomologacaoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Autorizacao", Namespace="http://tempuri.org/")]
    public partial class Autorizacao : object
    {
        
        private string data_emissaoField;
        
        private byte natureza_operacaoField;
        
        private string regime_especial_tributacaoField;
        
        private bool optante_simples_nacionalField;
        
        private string incentivador_culturalField;
        
        private string tributacao_rpsField;
        
        private string codigo_obraField;
        
        private string artField;
        
        private byte consumidor_finalField;
        
        private decimal percentual_total_tributos_simples_nacionalField;
        
        private byte indicador_destinatarioField;
        
        private WebZi.Plataform.Data.WSnfse.Prestador prestadorField;
        
        private WebZi.Plataform.Data.WSnfse.Tomador tomadorField;
        
        private WebZi.Plataform.Data.WSnfse.Servico servicoField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string data_emissao
        {
            get
            {
                return this.data_emissaoField;
            }
            set
            {
                this.data_emissaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public byte natureza_operacao
        {
            get
            {
                return this.natureza_operacaoField;
            }
            set
            {
                this.natureza_operacaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string regime_especial_tributacao
        {
            get
            {
                return this.regime_especial_tributacaoField;
            }
            set
            {
                this.regime_especial_tributacaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public bool optante_simples_nacional
        {
            get
            {
                return this.optante_simples_nacionalField;
            }
            set
            {
                this.optante_simples_nacionalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string incentivador_cultural
        {
            get
            {
                return this.incentivador_culturalField;
            }
            set
            {
                this.incentivador_culturalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string tributacao_rps
        {
            get
            {
                return this.tributacao_rpsField;
            }
            set
            {
                this.tributacao_rpsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string codigo_obra
        {
            get
            {
                return this.codigo_obraField;
            }
            set
            {
                this.codigo_obraField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string art
        {
            get
            {
                return this.artField;
            }
            set
            {
                this.artField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public byte consumidor_final
        {
            get
            {
                return this.consumidor_finalField;
            }
            set
            {
                this.consumidor_finalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public decimal percentual_total_tributos_simples_nacional
        {
            get
            {
                return this.percentual_total_tributos_simples_nacionalField;
            }
            set
            {
                this.percentual_total_tributos_simples_nacionalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public byte indicador_destinatario
        {
            get
            {
                return this.indicador_destinatarioField;
            }
            set
            {
                this.indicador_destinatarioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public WebZi.Plataform.Data.WSnfse.Prestador prestador
        {
            get
            {
                return this.prestadorField;
            }
            set
            {
                this.prestadorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public WebZi.Plataform.Data.WSnfse.Tomador tomador
        {
            get
            {
                return this.tomadorField;
            }
            set
            {
                this.tomadorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public WebZi.Plataform.Data.WSnfse.Servico servico
        {
            get
            {
                return this.servicoField;
            }
            set
            {
                this.servicoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Prestador", Namespace="http://tempuri.org/")]
    public partial class Prestador : object
    {
        
        private string cnpjField;
        
        private string inscricao_estadualField;
        
        private string inscricao_municipalField;
        
        private string codigo_municipioField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string cnpj
        {
            get
            {
                return this.cnpjField;
            }
            set
            {
                this.cnpjField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string inscricao_estadual
        {
            get
            {
                return this.inscricao_estadualField;
            }
            set
            {
                this.inscricao_estadualField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string inscricao_municipal
        {
            get
            {
                return this.inscricao_municipalField;
            }
            set
            {
                this.inscricao_municipalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string codigo_municipio
        {
            get
            {
                return this.codigo_municipioField;
            }
            set
            {
                this.codigo_municipioField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Tomador", Namespace="http://tempuri.org/")]
    public partial class Tomador : object
    {
        
        private string cnpjField;
        
        private string cpfField;
        
        private string razao_socialField;
        
        private string emailField;
        
        private string inscricao_municipalField;
        
        private string telefoneField;
        
        private WebZi.Plataform.Data.WSnfse.Endereco enderecoField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string cnpj
        {
            get
            {
                return this.cnpjField;
            }
            set
            {
                this.cnpjField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string cpf
        {
            get
            {
                return this.cpfField;
            }
            set
            {
                this.cpfField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string razao_social
        {
            get
            {
                return this.razao_socialField;
            }
            set
            {
                this.razao_socialField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string inscricao_municipal
        {
            get
            {
                return this.inscricao_municipalField;
            }
            set
            {
                this.inscricao_municipalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string telefone
        {
            get
            {
                return this.telefoneField;
            }
            set
            {
                this.telefoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public WebZi.Plataform.Data.WSnfse.Endereco endereco
        {
            get
            {
                return this.enderecoField;
            }
            set
            {
                this.enderecoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Servico", Namespace="http://tempuri.org/")]
    public partial class Servico : object
    {
        
        private string aliquotaField;
        
        private string discriminacaoField;
        
        private bool iss_retidoField;
        
        private string item_lista_servicoField;
        
        private string codigo_tributario_municipioField;
        
        private string valor_servicosField;
        
        private string valor_deducoesField;
        
        private string valor_pisField;
        
        private string valor_cofinsField;
        
        private string valor_inssField;
        
        private string valor_irField;
        
        private string valor_csllField;
        
        private string valor_issField;
        
        private string valor_iss_retidoField;
        
        private string outras_retencoesField;
        
        private string base_calculoField;
        
        private string desconto_incondicionadoField;
        
        private string desconto_condicionadoField;
        
        private string codigo_cnaeField;
        
        private string codigo_municipioField;
        
        private string percentual_total_tributosField;
        
        private string fonte_total_tributosField;
        
        private string codigo_tributacao_nacional_issField;
        
        private string codigo_nbsField;
        
        private string ibs_cbs_classificacao_tributariaField;
        
        private string ibs_cbs_situacao_tributariaField;
        
        private string codigo_indicador_operacaoField;
        
        private string codigo_municipio_incidenciaField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string aliquota
        {
            get
            {
                return this.aliquotaField;
            }
            set
            {
                this.aliquotaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string discriminacao
        {
            get
            {
                return this.discriminacaoField;
            }
            set
            {
                this.discriminacaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool iss_retido
        {
            get
            {
                return this.iss_retidoField;
            }
            set
            {
                this.iss_retidoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string item_lista_servico
        {
            get
            {
                return this.item_lista_servicoField;
            }
            set
            {
                this.item_lista_servicoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string codigo_tributario_municipio
        {
            get
            {
                return this.codigo_tributario_municipioField;
            }
            set
            {
                this.codigo_tributario_municipioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string valor_servicos
        {
            get
            {
                return this.valor_servicosField;
            }
            set
            {
                this.valor_servicosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string valor_deducoes
        {
            get
            {
                return this.valor_deducoesField;
            }
            set
            {
                this.valor_deducoesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string valor_pis
        {
            get
            {
                return this.valor_pisField;
            }
            set
            {
                this.valor_pisField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string valor_cofins
        {
            get
            {
                return this.valor_cofinsField;
            }
            set
            {
                this.valor_cofinsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string valor_inss
        {
            get
            {
                return this.valor_inssField;
            }
            set
            {
                this.valor_inssField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string valor_ir
        {
            get
            {
                return this.valor_irField;
            }
            set
            {
                this.valor_irField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string valor_csll
        {
            get
            {
                return this.valor_csllField;
            }
            set
            {
                this.valor_csllField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string valor_iss
        {
            get
            {
                return this.valor_issField;
            }
            set
            {
                this.valor_issField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string valor_iss_retido
        {
            get
            {
                return this.valor_iss_retidoField;
            }
            set
            {
                this.valor_iss_retidoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string outras_retencoes
        {
            get
            {
                return this.outras_retencoesField;
            }
            set
            {
                this.outras_retencoesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string base_calculo
        {
            get
            {
                return this.base_calculoField;
            }
            set
            {
                this.base_calculoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string desconto_incondicionado
        {
            get
            {
                return this.desconto_incondicionadoField;
            }
            set
            {
                this.desconto_incondicionadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public string desconto_condicionado
        {
            get
            {
                return this.desconto_condicionadoField;
            }
            set
            {
                this.desconto_condicionadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=18)]
        public string codigo_cnae
        {
            get
            {
                return this.codigo_cnaeField;
            }
            set
            {
                this.codigo_cnaeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=19)]
        public string codigo_municipio
        {
            get
            {
                return this.codigo_municipioField;
            }
            set
            {
                this.codigo_municipioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=20)]
        public string percentual_total_tributos
        {
            get
            {
                return this.percentual_total_tributosField;
            }
            set
            {
                this.percentual_total_tributosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=21)]
        public string fonte_total_tributos
        {
            get
            {
                return this.fonte_total_tributosField;
            }
            set
            {
                this.fonte_total_tributosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=22)]
        public string codigo_tributacao_nacional_iss
        {
            get
            {
                return this.codigo_tributacao_nacional_issField;
            }
            set
            {
                this.codigo_tributacao_nacional_issField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=23)]
        public string codigo_nbs
        {
            get
            {
                return this.codigo_nbsField;
            }
            set
            {
                this.codigo_nbsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=24)]
        public string ibs_cbs_classificacao_tributaria
        {
            get
            {
                return this.ibs_cbs_classificacao_tributariaField;
            }
            set
            {
                this.ibs_cbs_classificacao_tributariaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=25)]
        public string ibs_cbs_situacao_tributaria
        {
            get
            {
                return this.ibs_cbs_situacao_tributariaField;
            }
            set
            {
                this.ibs_cbs_situacao_tributariaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=26)]
        public string codigo_indicador_operacao
        {
            get
            {
                return this.codigo_indicador_operacaoField;
            }
            set
            {
                this.codigo_indicador_operacaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=27)]
        public string codigo_municipio_incidencia
        {
            get
            {
                return this.codigo_municipio_incidenciaField;
            }
            set
            {
                this.codigo_municipio_incidenciaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Endereco", Namespace="http://tempuri.org/")]
    public partial class Endereco : object
    {
        
        private string logradouroField;
        
        private string tipo_logradouroField;
        
        private string numeroField;
        
        private string complementoField;
        
        private string bairroField;
        
        private string codigo_municipioField;
        
        private string ufField;
        
        private string cepField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string logradouro
        {
            get
            {
                return this.logradouroField;
            }
            set
            {
                this.logradouroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string tipo_logradouro
        {
            get
            {
                return this.tipo_logradouroField;
            }
            set
            {
                this.tipo_logradouroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string numero
        {
            get
            {
                return this.numeroField;
            }
            set
            {
                this.numeroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string complemento
        {
            get
            {
                return this.complementoField;
            }
            set
            {
                this.complementoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string bairro
        {
            get
            {
                return this.bairroField;
            }
            set
            {
                this.bairroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string codigo_municipio
        {
            get
            {
                return this.codigo_municipioField;
            }
            set
            {
                this.codigo_municipioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string uf
        {
            get
            {
                return this.ufField;
            }
            set
            {
                this.ufField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string cep
        {
            get
            {
                return this.cepField;
            }
            set
            {
                this.cepField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Consulta", Namespace="http://tempuri.org/")]
    public partial class Consulta : object
    {
        
        private int GrvIdField;
        
        private int NfeIdField;
        
        private string IdentificadorNotaField;
        
        private int UsuarioIdField;
        
        private bool HomologacaoField;
        
        private bool BaixarImagemOriginalField;
        
        private string CnpjField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int GrvId
        {
            get
            {
                return this.GrvIdField;
            }
            set
            {
                this.GrvIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int NfeId
        {
            get
            {
                return this.NfeIdField;
            }
            set
            {
                this.NfeIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string IdentificadorNota
        {
            get
            {
                return this.IdentificadorNotaField;
            }
            set
            {
                this.IdentificadorNotaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int UsuarioId
        {
            get
            {
                return this.UsuarioIdField;
            }
            set
            {
                this.UsuarioIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public bool Homologacao
        {
            get
            {
                return this.HomologacaoField;
            }
            set
            {
                this.HomologacaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public bool BaixarImagemOriginal
        {
            get
            {
                return this.BaixarImagemOriginalField;
            }
            set
            {
                this.BaixarImagemOriginalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Cnpj
        {
            get
            {
                return this.CnpjField;
            }
            set
            {
                this.CnpjField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RetornoNotaFiscalEntity", Namespace="http://tempuri.org/")]
    public partial class RetornoNotaFiscalEntity : object
    {
        
        private string cnpj_prestadorField;
        
        private string refField;
        
        private string numero_rpsField;
        
        private string serie_rpsField;
        
        private string statusField;
        
        private string numeroField;
        
        private string codigo_verificacaoField;
        
        private System.DateTime data_emissaoField;
        
        private string urlField;
        
        private string caminho_xml_nota_fiscalField;
        
        private byte[] retorno_notaField;
        
        private byte[] ImagemNotaFiscalField;
        
        private WebZi.Plataform.Data.WSnfse.Erros[] errosField;
        
        private string HtmlField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string cnpj_prestador
        {
            get
            {
                return this.cnpj_prestadorField;
            }
            set
            {
                this.cnpj_prestadorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string @ref
        {
            get
            {
                return this.refField;
            }
            set
            {
                this.refField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string numero_rps
        {
            get
            {
                return this.numero_rpsField;
            }
            set
            {
                this.numero_rpsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string serie_rps
        {
            get
            {
                return this.serie_rpsField;
            }
            set
            {
                this.serie_rpsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string numero
        {
            get
            {
                return this.numeroField;
            }
            set
            {
                this.numeroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string codigo_verificacao
        {
            get
            {
                return this.codigo_verificacaoField;
            }
            set
            {
                this.codigo_verificacaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.DateTime data_emissao
        {
            get
            {
                return this.data_emissaoField;
            }
            set
            {
                this.data_emissaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string url
        {
            get
            {
                return this.urlField;
            }
            set
            {
                this.urlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string caminho_xml_nota_fiscal
        {
            get
            {
                return this.caminho_xml_nota_fiscalField;
            }
            set
            {
                this.caminho_xml_nota_fiscalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public byte[] retorno_nota
        {
            get
            {
                return this.retorno_notaField;
            }
            set
            {
                this.retorno_notaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public byte[] ImagemNotaFiscal
        {
            get
            {
                return this.ImagemNotaFiscalField;
            }
            set
            {
                this.ImagemNotaFiscalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public WebZi.Plataform.Data.WSnfse.Erros[] erros
        {
            get
            {
                return this.errosField;
            }
            set
            {
                this.errosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string Html
        {
            get
            {
                return this.HtmlField;
            }
            set
            {
                this.HtmlField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Erros", Namespace="http://tempuri.org/")]
    public partial class Erros : object
    {
        
        private string codigoField;
        
        private string mensagemField;
        
        private string correcaoField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string codigo
        {
            get
            {
                return this.codigoField;
            }
            set
            {
                this.codigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string mensagem
        {
            get
            {
                return this.mensagemField;
            }
            set
            {
                this.mensagemField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string correcao
        {
            get
            {
                return this.correcaoField;
            }
            set
            {
                this.correcaoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cancelamento", Namespace="http://tempuri.org/")]
    public partial class Cancelamento : object
    {
        
        private int GrvIdField;
        
        private string IdentificadorNotaField;
        
        private int UsuarioIdField;
        
        private string JustificativaField;
        
        private bool HomologacaoField;
        
        private string CnpjField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int GrvId
        {
            get
            {
                return this.GrvIdField;
            }
            set
            {
                this.GrvIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string IdentificadorNota
        {
            get
            {
                return this.IdentificadorNotaField;
            }
            set
            {
                this.IdentificadorNotaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int UsuarioId
        {
            get
            {
                return this.UsuarioIdField;
            }
            set
            {
                this.UsuarioIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Justificativa
        {
            get
            {
                return this.JustificativaField;
            }
            set
            {
                this.JustificativaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public bool Homologacao
        {
            get
            {
                return this.HomologacaoField;
            }
            set
            {
                this.HomologacaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Cnpj
        {
            get
            {
                return this.CnpjField;
            }
            set
            {
                this.CnpjField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    public class ArrayOfString : System.Collections.Generic.List<string>
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WebZi.Plataform.Data.WSnfse.WSnfseSoap")]
    public interface WSnfseSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SolicitarEmissaoNotaFiscal", ReplyAction="*")]
        System.Threading.Tasks.Task<WebZi.Plataform.Data.WSnfse.SolicitarEmissaoNotaFiscalResponse> SolicitarEmissaoNotaFiscalAsync(WebZi.Plataform.Data.WSnfse.SolicitarEmissaoNotaFiscalRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SolicitarEmissaoNotaFiscalAvulso", ReplyAction="*")]
        System.Threading.Tasks.Task<WebZi.Plataform.Data.WSnfse.SolicitarEmissaoNotaFiscalAvulsoResponse> SolicitarEmissaoNotaFiscalAvulsoAsync(WebZi.Plataform.Data.WSnfse.SolicitarEmissaoNotaFiscalAvulsoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReceberNotaFiscal", ReplyAction="*")]
        System.Threading.Tasks.Task<WebZi.Plataform.Data.WSnfse.ReceberNotaFiscalResponse> ReceberNotaFiscalAsync(WebZi.Plataform.Data.WSnfse.ReceberNotaFiscalRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReceberNotaFiscalAvulso", ReplyAction="*")]
        System.Threading.Tasks.Task<WebZi.Plataform.Data.WSnfse.ReceberNotaFiscalAvulsoResponse> ReceberNotaFiscalAvulsoAsync(WebZi.Plataform.Data.WSnfse.ReceberNotaFiscalAvulsoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CancelarNotaFiscal", ReplyAction="*")]
        System.Threading.Tasks.Task<WebZi.Plataform.Data.WSnfse.CancelarNotaFiscalResponse> CancelarNotaFiscalAsync(WebZi.Plataform.Data.WSnfse.CancelarNotaFiscalRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CancelarNotaFiscalAvulso", ReplyAction="*")]
        System.Threading.Tasks.Task<WebZi.Plataform.Data.WSnfse.CancelarNotaFiscalAvulsoResponse> CancelarNotaFiscalAvulsoAsync(WebZi.Plataform.Data.WSnfse.CancelarNotaFiscalAvulsoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GerarNotaFiscal", ReplyAction="*")]
        System.Threading.Tasks.Task<WebZi.Plataform.Data.WSnfse.GerarNotaFiscalResponse> GerarNotaFiscalAsync(WebZi.Plataform.Data.WSnfse.GerarNotaFiscalRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GerarNovaNotaFiscal", ReplyAction="*")]
        System.Threading.Tasks.Task<WebZi.Plataform.Data.WSnfse.GerarNovaNotaFiscalResponse> GerarNovaNotaFiscalAsync(WebZi.Plataform.Data.WSnfse.GerarNovaNotaFiscalRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SolicitarEmissaoNotaFiscalRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SolicitarEmissaoNotaFiscal", Namespace="http://tempuri.org/", Order=0)]
        public WebZi.Plataform.Data.WSnfse.SolicitarEmissaoNotaFiscalRequestBody Body;
        
        public SolicitarEmissaoNotaFiscalRequest()
        {
        }
        
        public SolicitarEmissaoNotaFiscalRequest(WebZi.Plataform.Data.WSnfse.SolicitarEmissaoNotaFiscalRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SolicitarEmissaoNotaFiscalRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebZi.Plataform.Data.WSnfse.CapaAutorizacaoNfse model;
        
        public SolicitarEmissaoNotaFiscalRequestBody()
        {
        }
        
        public SolicitarEmissaoNotaFiscalRequestBody(WebZi.Plataform.Data.WSnfse.CapaAutorizacaoNfse model)
        {
            this.model = model;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SolicitarEmissaoNotaFiscalResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SolicitarEmissaoNotaFiscalResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebZi.Plataform.Data.WSnfse.SolicitarEmissaoNotaFiscalResponseBody Body;
        
        public SolicitarEmissaoNotaFiscalResponse()
        {
        }
        
        public SolicitarEmissaoNotaFiscalResponse(WebZi.Plataform.Data.WSnfse.SolicitarEmissaoNotaFiscalResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SolicitarEmissaoNotaFiscalResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SolicitarEmissaoNotaFiscalResult;
        
        public SolicitarEmissaoNotaFiscalResponseBody()
        {
        }
        
        public SolicitarEmissaoNotaFiscalResponseBody(string SolicitarEmissaoNotaFiscalResult)
        {
            this.SolicitarEmissaoNotaFiscalResult = SolicitarEmissaoNotaFiscalResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SolicitarEmissaoNotaFiscalAvulsoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SolicitarEmissaoNotaFiscalAvulso", Namespace="http://tempuri.org/", Order=0)]
        public WebZi.Plataform.Data.WSnfse.SolicitarEmissaoNotaFiscalAvulsoRequestBody Body;
        
        public SolicitarEmissaoNotaFiscalAvulsoRequest()
        {
        }
        
        public SolicitarEmissaoNotaFiscalAvulsoRequest(WebZi.Plataform.Data.WSnfse.SolicitarEmissaoNotaFiscalAvulsoRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SolicitarEmissaoNotaFiscalAvulsoRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebZi.Plataform.Data.WSnfse.CapaAutorizacaoNfse model;
        
        public SolicitarEmissaoNotaFiscalAvulsoRequestBody()
        {
        }
        
        public SolicitarEmissaoNotaFiscalAvulsoRequestBody(WebZi.Plataform.Data.WSnfse.CapaAutorizacaoNfse model)
        {
            this.model = model;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SolicitarEmissaoNotaFiscalAvulsoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SolicitarEmissaoNotaFiscalAvulsoResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebZi.Plataform.Data.WSnfse.SolicitarEmissaoNotaFiscalAvulsoResponseBody Body;
        
        public SolicitarEmissaoNotaFiscalAvulsoResponse()
        {
        }
        
        public SolicitarEmissaoNotaFiscalAvulsoResponse(WebZi.Plataform.Data.WSnfse.SolicitarEmissaoNotaFiscalAvulsoResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SolicitarEmissaoNotaFiscalAvulsoResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SolicitarEmissaoNotaFiscalAvulsoResult;
        
        public SolicitarEmissaoNotaFiscalAvulsoResponseBody()
        {
        }
        
        public SolicitarEmissaoNotaFiscalAvulsoResponseBody(string SolicitarEmissaoNotaFiscalAvulsoResult)
        {
            this.SolicitarEmissaoNotaFiscalAvulsoResult = SolicitarEmissaoNotaFiscalAvulsoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReceberNotaFiscalRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReceberNotaFiscal", Namespace="http://tempuri.org/", Order=0)]
        public WebZi.Plataform.Data.WSnfse.ReceberNotaFiscalRequestBody Body;
        
        public ReceberNotaFiscalRequest()
        {
        }
        
        public ReceberNotaFiscalRequest(WebZi.Plataform.Data.WSnfse.ReceberNotaFiscalRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReceberNotaFiscalRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebZi.Plataform.Data.WSnfse.Consulta model;
        
        public ReceberNotaFiscalRequestBody()
        {
        }
        
        public ReceberNotaFiscalRequestBody(WebZi.Plataform.Data.WSnfse.Consulta model)
        {
            this.model = model;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReceberNotaFiscalResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReceberNotaFiscalResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebZi.Plataform.Data.WSnfse.ReceberNotaFiscalResponseBody Body;
        
        public ReceberNotaFiscalResponse()
        {
        }
        
        public ReceberNotaFiscalResponse(WebZi.Plataform.Data.WSnfse.ReceberNotaFiscalResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReceberNotaFiscalResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebZi.Plataform.Data.WSnfse.RetornoNotaFiscalEntity ReceberNotaFiscalResult;
        
        public ReceberNotaFiscalResponseBody()
        {
        }
        
        public ReceberNotaFiscalResponseBody(WebZi.Plataform.Data.WSnfse.RetornoNotaFiscalEntity ReceberNotaFiscalResult)
        {
            this.ReceberNotaFiscalResult = ReceberNotaFiscalResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReceberNotaFiscalAvulsoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReceberNotaFiscalAvulso", Namespace="http://tempuri.org/", Order=0)]
        public WebZi.Plataform.Data.WSnfse.ReceberNotaFiscalAvulsoRequestBody Body;
        
        public ReceberNotaFiscalAvulsoRequest()
        {
        }
        
        public ReceberNotaFiscalAvulsoRequest(WebZi.Plataform.Data.WSnfse.ReceberNotaFiscalAvulsoRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReceberNotaFiscalAvulsoRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebZi.Plataform.Data.WSnfse.Consulta model;
        
        public ReceberNotaFiscalAvulsoRequestBody()
        {
        }
        
        public ReceberNotaFiscalAvulsoRequestBody(WebZi.Plataform.Data.WSnfse.Consulta model)
        {
            this.model = model;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReceberNotaFiscalAvulsoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReceberNotaFiscalAvulsoResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebZi.Plataform.Data.WSnfse.ReceberNotaFiscalAvulsoResponseBody Body;
        
        public ReceberNotaFiscalAvulsoResponse()
        {
        }
        
        public ReceberNotaFiscalAvulsoResponse(WebZi.Plataform.Data.WSnfse.ReceberNotaFiscalAvulsoResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReceberNotaFiscalAvulsoResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebZi.Plataform.Data.WSnfse.RetornoNotaFiscalEntity ReceberNotaFiscalAvulsoResult;
        
        public ReceberNotaFiscalAvulsoResponseBody()
        {
        }
        
        public ReceberNotaFiscalAvulsoResponseBody(WebZi.Plataform.Data.WSnfse.RetornoNotaFiscalEntity ReceberNotaFiscalAvulsoResult)
        {
            this.ReceberNotaFiscalAvulsoResult = ReceberNotaFiscalAvulsoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CancelarNotaFiscalRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CancelarNotaFiscal", Namespace="http://tempuri.org/", Order=0)]
        public WebZi.Plataform.Data.WSnfse.CancelarNotaFiscalRequestBody Body;
        
        public CancelarNotaFiscalRequest()
        {
        }
        
        public CancelarNotaFiscalRequest(WebZi.Plataform.Data.WSnfse.CancelarNotaFiscalRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CancelarNotaFiscalRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebZi.Plataform.Data.WSnfse.Cancelamento model;
        
        public CancelarNotaFiscalRequestBody()
        {
        }
        
        public CancelarNotaFiscalRequestBody(WebZi.Plataform.Data.WSnfse.Cancelamento model)
        {
            this.model = model;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CancelarNotaFiscalResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CancelarNotaFiscalResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebZi.Plataform.Data.WSnfse.CancelarNotaFiscalResponseBody Body;
        
        public CancelarNotaFiscalResponse()
        {
        }
        
        public CancelarNotaFiscalResponse(WebZi.Plataform.Data.WSnfse.CancelarNotaFiscalResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CancelarNotaFiscalResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CancelarNotaFiscalResult;
        
        public CancelarNotaFiscalResponseBody()
        {
        }
        
        public CancelarNotaFiscalResponseBody(string CancelarNotaFiscalResult)
        {
            this.CancelarNotaFiscalResult = CancelarNotaFiscalResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CancelarNotaFiscalAvulsoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CancelarNotaFiscalAvulso", Namespace="http://tempuri.org/", Order=0)]
        public WebZi.Plataform.Data.WSnfse.CancelarNotaFiscalAvulsoRequestBody Body;
        
        public CancelarNotaFiscalAvulsoRequest()
        {
        }
        
        public CancelarNotaFiscalAvulsoRequest(WebZi.Plataform.Data.WSnfse.CancelarNotaFiscalAvulsoRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CancelarNotaFiscalAvulsoRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebZi.Plataform.Data.WSnfse.Cancelamento model;
        
        public CancelarNotaFiscalAvulsoRequestBody()
        {
        }
        
        public CancelarNotaFiscalAvulsoRequestBody(WebZi.Plataform.Data.WSnfse.Cancelamento model)
        {
            this.model = model;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CancelarNotaFiscalAvulsoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CancelarNotaFiscalAvulsoResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebZi.Plataform.Data.WSnfse.CancelarNotaFiscalAvulsoResponseBody Body;
        
        public CancelarNotaFiscalAvulsoResponse()
        {
        }
        
        public CancelarNotaFiscalAvulsoResponse(WebZi.Plataform.Data.WSnfse.CancelarNotaFiscalAvulsoResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CancelarNotaFiscalAvulsoResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CancelarNotaFiscalAvulsoResult;
        
        public CancelarNotaFiscalAvulsoResponseBody()
        {
        }
        
        public CancelarNotaFiscalAvulsoResponseBody(string CancelarNotaFiscalAvulsoResult)
        {
            this.CancelarNotaFiscalAvulsoResult = CancelarNotaFiscalAvulsoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GerarNotaFiscalRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GerarNotaFiscal", Namespace="http://tempuri.org/", Order=0)]
        public WebZi.Plataform.Data.WSnfse.GerarNotaFiscalRequestBody Body;
        
        public GerarNotaFiscalRequest()
        {
        }
        
        public GerarNotaFiscalRequest(WebZi.Plataform.Data.WSnfse.GerarNotaFiscalRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GerarNotaFiscalRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int grvId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int usuarioId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public bool isDev;
        
        public GerarNotaFiscalRequestBody()
        {
        }
        
        public GerarNotaFiscalRequestBody(int grvId, int usuarioId, bool isDev)
        {
            this.grvId = grvId;
            this.usuarioId = usuarioId;
            this.isDev = isDev;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GerarNotaFiscalResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GerarNotaFiscalResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebZi.Plataform.Data.WSnfse.GerarNotaFiscalResponseBody Body;
        
        public GerarNotaFiscalResponse()
        {
        }
        
        public GerarNotaFiscalResponse(WebZi.Plataform.Data.WSnfse.GerarNotaFiscalResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GerarNotaFiscalResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebZi.Plataform.Data.WSnfse.ArrayOfString GerarNotaFiscalResult;
        
        public GerarNotaFiscalResponseBody()
        {
        }
        
        public GerarNotaFiscalResponseBody(WebZi.Plataform.Data.WSnfse.ArrayOfString GerarNotaFiscalResult)
        {
            this.GerarNotaFiscalResult = GerarNotaFiscalResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GerarNovaNotaFiscalRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GerarNovaNotaFiscal", Namespace="http://tempuri.org/", Order=0)]
        public WebZi.Plataform.Data.WSnfse.GerarNovaNotaFiscalRequestBody Body;
        
        public GerarNovaNotaFiscalRequest()
        {
        }
        
        public GerarNovaNotaFiscalRequest(WebZi.Plataform.Data.WSnfse.GerarNovaNotaFiscalRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GerarNovaNotaFiscalRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int grvId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string identificadorNota;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int usuarioId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public bool isDev;
        
        public GerarNovaNotaFiscalRequestBody()
        {
        }
        
        public GerarNovaNotaFiscalRequestBody(int grvId, string identificadorNota, int usuarioId, bool isDev)
        {
            this.grvId = grvId;
            this.identificadorNota = identificadorNota;
            this.usuarioId = usuarioId;
            this.isDev = isDev;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GerarNovaNotaFiscalResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GerarNovaNotaFiscalResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebZi.Plataform.Data.WSnfse.GerarNovaNotaFiscalResponseBody Body;
        
        public GerarNovaNotaFiscalResponse()
        {
        }
        
        public GerarNovaNotaFiscalResponse(WebZi.Plataform.Data.WSnfse.GerarNovaNotaFiscalResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GerarNovaNotaFiscalResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebZi.Plataform.Data.WSnfse.ArrayOfString GerarNovaNotaFiscalResult;
        
        public GerarNovaNotaFiscalResponseBody()
        {
        }
        
        public GerarNovaNotaFiscalResponseBody(WebZi.Plataform.Data.WSnfse.ArrayOfString GerarNovaNotaFiscalResult)
        {
            this.GerarNovaNotaFiscalResult = GerarNovaNotaFiscalResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface WSnfseSoapChannel : WebZi.Plataform.Data.WSnfse.WSnfseSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class WSnfseSoapClient : System.ServiceModel.ClientBase<WebZi.Plataform.Data.WSnfse.WSnfseSoap>, WebZi.Plataform.Data.WSnfse.WSnfseSoap
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar o ponto de extremidade de serviço.
        /// </summary>
        /// <param name="serviceEndpoint">O ponto de extremidade a ser configurado</param>
        /// <param name="clientCredentials">As credenciais do cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public WSnfseSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(WSnfseSoapClient.GetBindingForEndpoint(endpointConfiguration), WSnfseSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WSnfseSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(WSnfseSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WSnfseSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(WSnfseSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WSnfseSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebZi.Plataform.Data.WSnfse.SolicitarEmissaoNotaFiscalResponse> WebZi.Plataform.Data.WSnfse.WSnfseSoap.SolicitarEmissaoNotaFiscalAsync(WebZi.Plataform.Data.WSnfse.SolicitarEmissaoNotaFiscalRequest request)
        {
            return base.Channel.SolicitarEmissaoNotaFiscalAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebZi.Plataform.Data.WSnfse.SolicitarEmissaoNotaFiscalResponse> SolicitarEmissaoNotaFiscalAsync(WebZi.Plataform.Data.WSnfse.CapaAutorizacaoNfse model)
        {
            WebZi.Plataform.Data.WSnfse.SolicitarEmissaoNotaFiscalRequest inValue = new WebZi.Plataform.Data.WSnfse.SolicitarEmissaoNotaFiscalRequest();
            inValue.Body = new WebZi.Plataform.Data.WSnfse.SolicitarEmissaoNotaFiscalRequestBody();
            inValue.Body.model = model;
            return ((WebZi.Plataform.Data.WSnfse.WSnfseSoap)(this)).SolicitarEmissaoNotaFiscalAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebZi.Plataform.Data.WSnfse.SolicitarEmissaoNotaFiscalAvulsoResponse> WebZi.Plataform.Data.WSnfse.WSnfseSoap.SolicitarEmissaoNotaFiscalAvulsoAsync(WebZi.Plataform.Data.WSnfse.SolicitarEmissaoNotaFiscalAvulsoRequest request)
        {
            return base.Channel.SolicitarEmissaoNotaFiscalAvulsoAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebZi.Plataform.Data.WSnfse.SolicitarEmissaoNotaFiscalAvulsoResponse> SolicitarEmissaoNotaFiscalAvulsoAsync(WebZi.Plataform.Data.WSnfse.CapaAutorizacaoNfse model)
        {
            WebZi.Plataform.Data.WSnfse.SolicitarEmissaoNotaFiscalAvulsoRequest inValue = new WebZi.Plataform.Data.WSnfse.SolicitarEmissaoNotaFiscalAvulsoRequest();
            inValue.Body = new WebZi.Plataform.Data.WSnfse.SolicitarEmissaoNotaFiscalAvulsoRequestBody();
            inValue.Body.model = model;
            return ((WebZi.Plataform.Data.WSnfse.WSnfseSoap)(this)).SolicitarEmissaoNotaFiscalAvulsoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebZi.Plataform.Data.WSnfse.ReceberNotaFiscalResponse> WebZi.Plataform.Data.WSnfse.WSnfseSoap.ReceberNotaFiscalAsync(WebZi.Plataform.Data.WSnfse.ReceberNotaFiscalRequest request)
        {
            return base.Channel.ReceberNotaFiscalAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebZi.Plataform.Data.WSnfse.ReceberNotaFiscalResponse> ReceberNotaFiscalAsync(WebZi.Plataform.Data.WSnfse.Consulta model)
        {
            WebZi.Plataform.Data.WSnfse.ReceberNotaFiscalRequest inValue = new WebZi.Plataform.Data.WSnfse.ReceberNotaFiscalRequest();
            inValue.Body = new WebZi.Plataform.Data.WSnfse.ReceberNotaFiscalRequestBody();
            inValue.Body.model = model;
            return ((WebZi.Plataform.Data.WSnfse.WSnfseSoap)(this)).ReceberNotaFiscalAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebZi.Plataform.Data.WSnfse.ReceberNotaFiscalAvulsoResponse> WebZi.Plataform.Data.WSnfse.WSnfseSoap.ReceberNotaFiscalAvulsoAsync(WebZi.Plataform.Data.WSnfse.ReceberNotaFiscalAvulsoRequest request)
        {
            return base.Channel.ReceberNotaFiscalAvulsoAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebZi.Plataform.Data.WSnfse.ReceberNotaFiscalAvulsoResponse> ReceberNotaFiscalAvulsoAsync(WebZi.Plataform.Data.WSnfse.Consulta model)
        {
            WebZi.Plataform.Data.WSnfse.ReceberNotaFiscalAvulsoRequest inValue = new WebZi.Plataform.Data.WSnfse.ReceberNotaFiscalAvulsoRequest();
            inValue.Body = new WebZi.Plataform.Data.WSnfse.ReceberNotaFiscalAvulsoRequestBody();
            inValue.Body.model = model;
            return ((WebZi.Plataform.Data.WSnfse.WSnfseSoap)(this)).ReceberNotaFiscalAvulsoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebZi.Plataform.Data.WSnfse.CancelarNotaFiscalResponse> WebZi.Plataform.Data.WSnfse.WSnfseSoap.CancelarNotaFiscalAsync(WebZi.Plataform.Data.WSnfse.CancelarNotaFiscalRequest request)
        {
            return base.Channel.CancelarNotaFiscalAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebZi.Plataform.Data.WSnfse.CancelarNotaFiscalResponse> CancelarNotaFiscalAsync(WebZi.Plataform.Data.WSnfse.Cancelamento model)
        {
            WebZi.Plataform.Data.WSnfse.CancelarNotaFiscalRequest inValue = new WebZi.Plataform.Data.WSnfse.CancelarNotaFiscalRequest();
            inValue.Body = new WebZi.Plataform.Data.WSnfse.CancelarNotaFiscalRequestBody();
            inValue.Body.model = model;
            return ((WebZi.Plataform.Data.WSnfse.WSnfseSoap)(this)).CancelarNotaFiscalAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebZi.Plataform.Data.WSnfse.CancelarNotaFiscalAvulsoResponse> WebZi.Plataform.Data.WSnfse.WSnfseSoap.CancelarNotaFiscalAvulsoAsync(WebZi.Plataform.Data.WSnfse.CancelarNotaFiscalAvulsoRequest request)
        {
            return base.Channel.CancelarNotaFiscalAvulsoAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebZi.Plataform.Data.WSnfse.CancelarNotaFiscalAvulsoResponse> CancelarNotaFiscalAvulsoAsync(WebZi.Plataform.Data.WSnfse.Cancelamento model)
        {
            WebZi.Plataform.Data.WSnfse.CancelarNotaFiscalAvulsoRequest inValue = new WebZi.Plataform.Data.WSnfse.CancelarNotaFiscalAvulsoRequest();
            inValue.Body = new WebZi.Plataform.Data.WSnfse.CancelarNotaFiscalAvulsoRequestBody();
            inValue.Body.model = model;
            return ((WebZi.Plataform.Data.WSnfse.WSnfseSoap)(this)).CancelarNotaFiscalAvulsoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebZi.Plataform.Data.WSnfse.GerarNotaFiscalResponse> WebZi.Plataform.Data.WSnfse.WSnfseSoap.GerarNotaFiscalAsync(WebZi.Plataform.Data.WSnfse.GerarNotaFiscalRequest request)
        {
            return base.Channel.GerarNotaFiscalAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebZi.Plataform.Data.WSnfse.GerarNotaFiscalResponse> GerarNotaFiscalAsync(int grvId, int usuarioId, bool isDev)
        {
            WebZi.Plataform.Data.WSnfse.GerarNotaFiscalRequest inValue = new WebZi.Plataform.Data.WSnfse.GerarNotaFiscalRequest();
            inValue.Body = new WebZi.Plataform.Data.WSnfse.GerarNotaFiscalRequestBody();
            inValue.Body.grvId = grvId;
            inValue.Body.usuarioId = usuarioId;
            inValue.Body.isDev = isDev;
            return ((WebZi.Plataform.Data.WSnfse.WSnfseSoap)(this)).GerarNotaFiscalAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebZi.Plataform.Data.WSnfse.GerarNovaNotaFiscalResponse> WebZi.Plataform.Data.WSnfse.WSnfseSoap.GerarNovaNotaFiscalAsync(WebZi.Plataform.Data.WSnfse.GerarNovaNotaFiscalRequest request)
        {
            return base.Channel.GerarNovaNotaFiscalAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebZi.Plataform.Data.WSnfse.GerarNovaNotaFiscalResponse> GerarNovaNotaFiscalAsync(int grvId, string identificadorNota, int usuarioId, bool isDev)
        {
            WebZi.Plataform.Data.WSnfse.GerarNovaNotaFiscalRequest inValue = new WebZi.Plataform.Data.WSnfse.GerarNovaNotaFiscalRequest();
            inValue.Body = new WebZi.Plataform.Data.WSnfse.GerarNovaNotaFiscalRequestBody();
            inValue.Body.grvId = grvId;
            inValue.Body.identificadorNota = identificadorNota;
            inValue.Body.usuarioId = usuarioId;
            inValue.Body.isDev = isDev;
            return ((WebZi.Plataform.Data.WSnfse.WSnfseSoap)(this)).GerarNovaNotaFiscalAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WSnfseSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.WSnfseSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Não foi possível encontrar o ponto de extremidade com o nome \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WSnfseSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://api.notafiscal.gestordepatios.app.br/WSnfse.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.WSnfseSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://api.notafiscal.gestordepatios.app.br/WSnfse.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Não foi possível encontrar o ponto de extremidade com o nome \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            WSnfseSoap,
            
            WSnfseSoap12,
        }
    }
}
